controller_list:
  - name: fake_limb_fl_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_fl_j
      - leg_fl_j
      - foreleg_fl_j
  - name: fake_limb_bl_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_bl_j
      - leg_bl_j
      - foreleg_bl_j
  - name: fake_limb_fr_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_fr_j
      - leg_fr_j
      - foreleg_fr_j
  - name: fake_limb_br_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_br_j
      - leg_br_j
      - foreleg_br_j
initial:  # Define initial robot poses per group
  - group: limb_fl
    pose: posefl0
  - group: limb_bl
    pose: posebl1
  - group: limb_fr
    pose: posefr0
  - group: limb_br
    pose: posebr0