# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - dog_fl_controller

  dog_fl_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - shoulder_fl_j
      - leg_fl_j
      - foreleg_fl_j
    action_ns: follow_joint_trajectory
    default: true