limb_fl_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - shoulder_fl_j
    - leg_fl_j
    - foreleg_fl_j
  gains:
    shoulder_fl_j:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    leg_fl_j:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    foreleg_fl_j:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
limb_bl_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - shoulder_bl_j
    - leg_bl_j
    - foreleg_bl_j
  gains:
    shoulder_bl_j:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    leg_bl_j:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    foreleg_bl_j:
      p: 100
      d: 1
      i: 1
      i_clamp: 1