controller_list:
  - name: limb_fl_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - shoulder_fl_j
      - leg_fl_j
      - foreleg_fl_j
  - name: limb_bl_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - shoulder_bl_j
      - leg_bl_j
      - foreleg_bl_j
  - name: limb_fr_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - shoulder_fr_j
      - leg_fr_j
      - foreleg_fr_j
  - name: limb_br_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - shoulder_br_j
      - leg_br_j
      - foreleg_br_j